apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  labels:
    app.kubernetes.io/instance: lerke
  name: lerke-secrets
  namespace: lerke
spec:
  itemPath: vaults/kube/items/lerke-secrets
